--Q1. What is the total revenue generated by male vs female customers?
select gender, sum(purchase_amount) as revenue
from customer
group by gender
--Q2. which customer used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer)

--Q3. which are the top 5 products with the highest average review rating?
select item_purchased, (avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4. Compare the average Purchase amounts between standard and express shipping.
select shipping_type,
Avg(purchase_amount)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribers customers spend more? compare average spend and total revenue between subscribers and non subscribers
select subscription_status,
count(customer_id) as total_customers,
ROUND(avg(purchase_amount),2) as avg_spend,
ROUND(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--Q6. which 5 products have the highest percentage of purchases with discount applied?
select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;






